name: Deploy Frontend

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Build check
        run: |
          npm install
          npm run build

      - name: Deploy
        run: |
          echo "${{ secrets.ROOT_PASSWORD }}" | su -c "
            cd /var/www/html/frontend_cem &&
            git pull origin develop &&
            docker compose down &&
            docker compose up -d --build
          " root
